### ISSUE TITLE
Doesn't follow desktop theme (Flatpak/Fedora)

### ISSUE THREAD

**Issue by M00NJ** [edfloreshz/tasks#22]
I just installed the flatpak on Fedora running COSMIC DE and the app looks and works great! :)
Though in my configuration it doesn't seem to pick up the user selected theme. It always uses the default theme and doesn't respect changes to the accent color, dark/light preference, or removal of the minimize/maximize buttons.

**Comment by edfloreshz** [comment]
I'm working to enable this, should be fixed in the next version.

**Comment by edfloreshz** [comment]
Fixed by 3786d06bfcff83d1b749c08cee985ce236dc4ad8
